### ISSUE TITLE
Please display the Coronal, Sagittal and Axial Image. Don't use Axial Image to display all 3 image type.

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#15]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 13:59 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/12_

----

**Comment by yogii1981** [comment]
what is the status of this @shengt? I had a conversation with @leeight and he informed that he has no idea how to construct Sagittal and Coronal Image from the Axial Image!

**Comment by tommy-qichang** [comment]
I can show Yubei @leeight how it works.

**Comment by shengt** [comment]
@yogii1981 I've created the function to generate jpg files from the hdf5. Needs to integrated it into the process, when the cloud receives the hdf5 file from mozart, trigger the function. It's still in progress.

**Comment by shengt** [comment]
story point +3

**Comment by yogii1981** [comment]
@leeight @shengt what is the update of this story?

**Comment by leeight** [comment]
Assign myself.

**Comment by leeight** [comment]
颜色不太正常

![image](https://user-images.githubusercontent.com/104052/34780742-e0d8f95e-f65e-11e7-8102-c202b7ff80bc.png)

**Comment by shengt** [comment]
Please try these JSON files. CORS is enabled

http://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/axial/0.json ... 227.json

http://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/coronal/0.json ... 512.json

http://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/sagittal/0.json ... 512.json

**Comment by leeight** [comment]
昨天测试之后，发现颜色不对，然后对比了一下 image 的格式，参数并不完全一致。

主要有差异的参数如下：

* columnPixelSpacing
* rowPixelSpacing
* intercept
* windowCenter
* windowWidth

试了试，因为我们默认值是 `intercept` 是 `0`，但是从 dicom 里面解析出来的值是 `-1024` 这个导致了色彩的差异

**Comment by leeight** [comment]
```js
const voiLutModule = cornerstone.metaData.get('voiLutModule', imageId);
    const modalityLUTOutputPixelRepresentation = getModalityLUTOutputPixelRepresentation(dataSet);
    return {
      windowCenter: getNumberValues(dataSet, 'x00281050', 1),
      windowWidth: getNumberValues(dataSet, 'x00281051', 1),
      voiLUTSequence: getLUTs(modalityLUTOutputPixelRepresentation, dataSet.elements.x00283010)
    };

const modalityLutModule = cornerstone.metaData.get('modalityLutModule', imageId);
    {
      rescaleIntercept: dataSet.floatString('x00281052'),
      rescaleSlope: dataSet.floatString('x00281053'),
      rescaleType: dataSet.string('x00281054'),
      modalityLUTSequence: getLUTs(dataSet.uint16('x00280103'), dataSet.elements.x00283000)
    };

const imagePlaneModule = cornerstone.metaData.get('imagePlaneModule', imageId);
    {
      pixelSpacing: getNumberValues(dataSet, 'x00280030', 2),
      imageOrientationPatient: getNumberValues(dataSet, 'x00200037', 6),
      imagePositionPatient: getNumberValues(dataSet, 'x00200032', 3),
      sliceThickness: dataSet.floatString('x00180050'),
      sliceLocation: dataSet.floatString('x00201041'),
      frameOfReferenceUID: dataSet.string('x00200052')
    };

// ------

{
  intercept: modalityLutModule.rescaleIntercept ? modalityLutModule.rescaleIntercept : 0,
  windowCenter: voiLutModule.windowCenter ? voiLutModule.windowCenter[0] : undefined,
  windowWidth: voiLutModule.windowWidth ? voiLutModule.windowWidth[0] : undefined,
  columnPixelSpacing: imagePlaneModule.pixelSpacing ? imagePlaneModule.pixelSpacing[1] : undefined,
  rowPixelSpacing: imagePlaneModule.pixelSpacing ? imagePlaneModule.pixelSpacing[0] : undefined,
}
```

**Comment by leeight** [comment]
@shengt 现在 DEMO 环境是更新了一下数据，<http://demo.cleerlymedcloud.com/#/case/2>，这里面的 `axial` 和 `coronal` 是用 JSON 渲染出来的

**Comment by shengt** [comment]
Let me see if I can get these values from the raw dicom file.

**Comment by shengt** [comment]
@leeight I updated API doc
https://github.com/Cleerly/ccs-api/blob/master/docs/openapi.yml

- Added metadata in GET /lab/cases/{caseId}/series/{seriesId}/viewer, including pixelSpacing and intercept
- Merged columnPixelSpacing and rowPixelSpacing to pixelSpacing in GET /lab/cases/{caseId}/series/{seriesId}/vessels/{vesselId}

DICOM has only `pixelSpacing`. So columnPixelSpacing and rowPixelSpacing are the same

```
{
  "metadata": {
    "pixelSpacing": 0,
    "intercept": 0
  },
  "axial": {
    "width": 0,
    "height": 0,
    "frames": [
      "string"
    ]
  },
  "coronal": {
    "width": 0,
    "height": 0,
    "frames": [
      "string"
    ]
  },
  "sagittal": {
    "width": 0,
    "height": 0,
    "frames": [
      "string"
    ]
  }
}
```

**Comment by leeight** [comment]
OK

**Comment by yogii1981** [comment]
Axial Image is not looking right and is not displayed properly.

**Comment by yogii1981** [comment]
<img width="590" alt="screen shot 2018-01-18 at 6 49 16 pm" src="https://user-images.githubusercontent.com/8645346/35127489-639c5620-fc80-11e7-881c-ef37e5d07605.png">

**Comment by yogii1981** [comment]
@leeight : 
1. Axial, Sagittal and Coronal images are not visible correctly.
2. Also, Images the way are displayed is not correct. This needs to be fixed.

**Comment by shengt** [comment]
@leeight I've updated the new json files in S3.
Same urls. You should be able to use them directly. The CORS is enabled.

https://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/axial/0.json ... 227.json

https://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/coronal/0.json ... 511.json

https://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/sagittal/0.json ... 511.json

**Comment by leeight** [comment]
Ok, I'll update the mockup data today.

**Comment by leeight** [comment]
@shengt 

> Failed to load https://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/axial/0.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

需要配置一下 `http://localhost:3000` 这个 Origin

**Comment by leeight** [comment]
![image](https://user-images.githubusercontent.com/104052/35337353-e51a14ba-0155-11e8-9500-6570ee759d9c.png)

**Comment by shengt** [comment]
Weird. only axial images have no CORS enabled. Coronal and sagittal images are fine. I'll check what's going on. There were an error when uploading axial images.

**Comment by shengt** [comment]
Re-upload the axial image. now images are looking good. However, they are very slow.
1. I see the request header has `Cache control: no-cache`. is that on purpose?
2. We can open another ticket for the performance optimization.

**Comment by leeight** [comment]
@shengt It's not on purpose, actually i can't modify the `Cache-Control` request header. But i think you should add `Cache-Control: public, max-age=999999999` on the response header for better caching mechanisms.

```
curl -I https://cdn-dev.cleerlymedcloud.com/4f03ab24-0aaf-4ded-831c-c43ebaf7feb4/SS_Segment_30_74_BPM_0_625mm_5340/axial/0.json
```
----

```
HTTP/2 200 
content-type: application/json
content-length: 1132340
date: Thu, 25 Jan 2018 07:55:47 GMT
last-modified: Wed, 24 Jan 2018 22:10:27 GMT
etag: "d1434ca8c4f289e77639c9fafc04a793"
accept-ranges: bytes
server: AmazonS3
vary: Accept-Encoding
x-cache: Miss from cloudfront
via: 1.1 8f3313a9a7b94884892dfae6426d7a22.cloudfront.net (CloudFront)
x-amz-cf-id: 3eMD3fwSL33YAtnrEmg8UwNnEUdXDM_PahHG-fJEeyn4LPIjaL24QQ==
```

**Comment by leeight** [comment]
> However, they are very slow.
I think we can add a progress indicator to show how many images have been loaded.
