### ISSUE TITLE
[CLOSED] Why series type is not changing the straightened segments? 

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#17]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:00 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/14_

----

Unable to change series type from series 1 to series 2 etc. Please fix this issue.

**Comment by shengt** [comment]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:07 GMT_

----

can not reproduce

**Comment by shengt** [comment]
<a href="https://github.com/yogii1981"><img src="https://avatars2.githubusercontent.com/u/8645346?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yogii1981](https://github.com/yogii1981)**
_Wednesday Nov 29, 2017 at 20:39 GMT_

----

It seems to be working fine right now!

**Comment by yogii1981** [comment]
All right we will re-test this feature in MVP1 and Siemens- II Demo @shengt
