### ISSUE TITLE
 FRHP-022 : Distance - why distance measurement goes away once the user draw it. It should display the selected line and distance and right click should allow user to erase it. or some better feature.

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#18]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:00 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/15_

----

**Comment by yogii1981** [comment]
Where should I perform to test this feature? in Demo link or the development link which we were using earlier? @shengt @leeight

**Comment by shengt** [comment]
demo.cleerlymedcloud.com

**Comment by yogii1981** [comment]
@leeight @shengt I am opening this issue.

When I selected a distance between two points, I was able to see the distance between two points but I couldn't able to erase or delete the line later on.

**Comment by yogii1981** [comment]
After a discussion with Yuibei, we have determined that it should be done before 7th January but can be ignored for 22nd Dec demo if too many stories which have higher priorities need to be finished.

**Comment by leeight** [comment]
@yogii1981 

The demo environment updated, now you can remove the distance measurement.

<http://demo.cleerlymedcloud.com/#/case/2>

![image](https://user-images.githubusercontent.com/104052/34080806-b35140ec-e37e-11e7-8932-b6bafa68290a.png)

**Comment by yogii1981** [comment]
It's working fine for series 1 but not for series 2 ? cc: @leeight
