### ISSUE TITLE
Segment - Already mentioned in functional requirement FRQC-022, FRQC-022.1, FRQC-022.2, FRQC-022.3

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#19]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:01 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/16_

----

**Comment by shengt** [comment]
From @leeight :
@yogii1981

    FRQC-022: The system shall allow the user to accept/edit/reject the stenosis region identified by mozart (Computational Model).
    FRQC-022.1: The system shall have button which allow user to select “ yes / no”  to accept or reject the stenosis.
    FRQC-022.2: The system shall have ability to mark the stenosis with straightened line.
    FRQC-022.3: The system shall have ability to name identified region of the stenosis on the image.

It looks like FRQC-022 is about stenosis not segments, so what could you provide more info for this issue?

**Comment by yogii1981** [comment]
@samuraimeow In this requirement, If stenosis has been identified Mozart then VisionLab Analyst shall see the **pop-up button** which is asking VisionLab user to confirm. "yes/ No" Whether stenosis is present or not.

**Comment by yogii1981** [comment]
https://docs.google.com/document/d/1E6YJlR15oJ9I2wuXXZvrsW6n8RrBFGm2zr-UnqZB79U/edit#

**Comment by leeight** [comment]
@yogii1981 I think this issue is duplicated with #25 .
