### ISSUE TITLE
FRQC-052, 05.1,052.2  CTO 

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#20]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:01 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/17_

----

**Comment by yogii1981** [comment]
** Requirements / User Stories**


FRQC-052 | The system shall have a tool which allow the user to draw a  straight line which allows the user to draw two horizontal line to indicate the starting and ending of the CTO.

FRQC-052.1 | The system auto- calculates the length of CTO between two horizontal lines.
FRQC-052.2 | The system shall automatically generate the smallest lumen wall between A and B horizontal line with a constant radius of 1 mm.


4.

**Comment by yogii1981** [comment]
I will add the acceptance criteria tomorrow.

**Comment by leeight** [comment]
@yogii1981 What it will look like after reviewer add CTO annotation? Could you upload a screenshot?

**Comment by leeight** [comment]
@yogii1981 After user draw two straight lines (the blue color), what's the next step?

![untitled-1](https://user-images.githubusercontent.com/104052/34113079-85873808-e449-11e7-870b-e515453b0271.png)

**Comment by yogii1981** [comment]
Calcified Plaque: A pixel unit of more than 350 Houndsfield Unit

Non-calcified Plaque: A pixel unit of less than 350 HU.

**Comment by yogii1981** [comment]
In between two horizontal line A & B : 

1 . Calculate the volume of the region between A and B.
2. Based on the pixel units, calculate the volume of calcified plaque in CTO (between A and B)
3. Based on the pixel units, calculate the volume of non-calcified plaque in CTO (between A and B)

**Comment by leeight** [comment]
Make the start position and end position moveable.
Test environment updated: http://demo.cleerlymedcloud.com/#/case/2

**Comment by leeight** [comment]
https://www.youtube.com/watch?v=12Vc2dR-hbs&feature=youtu.be
