### ISSUE TITLE
FRQC-057  Spotty Calcification

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#23]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:02 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/20_

----
**Requirement/User Story**

**FRQC-057 | The system shall have a tool which allows the user to mark the region where spotty calcification exists using the straightened segment.**

**Spotty Calcification is 6 continuous slices or less than 3 mm.**

**It is equal to or Greater than 350 HU.Spotty Calcification => 350HU(less than 3mm).**

**The marker should be "marked" outside the vessel image need to create a region of interest.**

**The user shall be able to accept/ reject/mark/move the spotty calcification**

Feature to Accept/ reject
-- | --

** Acceptance Criteria**

**Comment by yogii1981** [comment]
updated the requirement. @leeight @shengt

**Comment by yogii1981** [comment]
<img width="219" alt="screen shot 2017-12-13 at 5 30 57 pm" src="https://user-images.githubusercontent.com/8645346/33965858-70c8ca20-e02b-11e7-942a-3f14c7755e88.png">

**Comment by yogii1981** [comment]
** A vertical line marking the region where Spotty calcification exists**

**Comment by yogii1981** [comment]
Test successfully.
