### ISSUE TITLE
Cross section and Straightened segment should be connected and changes made on either of them should be reflected on all of them . All the straightened segment as well as cross section

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#24]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 14:02 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/21_

----

**Comment by leeight** [comment]
![issue-24](https://user-images.githubusercontent.com/104052/33610878-91e61200-da07-11e7-98de-65c79e8c198b.gif)


@yogii1981 @shengt
