### ISSUE TITLE
Stenosis _ Feature

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#25]
<a href="https://github.com/yogii1981"><img src="https://avatars2.githubusercontent.com/u/8645346?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yogii1981](https://github.com/yogii1981)**
_Wednesday Nov 29, 2017 at 20:00 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/22_

----

**Requirements/ User Story**
FRQC-022 | The system shall allow the user to accept/edit/reject the stenosis region identified by mozart (Computational Model).

FRQC-022.1 | The system shall have a button which allows the user to select “Yes/ No”  to accept or reject the stenosis.
FRQC-022.2 | The system shall have the ability to mark the stenosis with the straightened line - Horizontal. (** TOOL**)
FRQC-022.3 | The system shall have the ability to name identified region of the stenosis on the image [User shouldn’t be going on the top of the browser to add the name every time]. R1, PM, O, DM, R2.
FRQC-022.4 | The system shall auto-populate the different points of Stenosis - R1, PM, O, DM, R2.
R1 - Start point of Stenosis region; PM: Proximal of Stenosis; O:  Maximum stenosis point; DM - Distal of the Stenosis; R2 - Endpoint of the Stenosis region.
FRQC-022.5 | The system shall allow the user to move points but they should always remain in this given order  R1, PM, O, DM, R2.

**Acceptance Criteria** (AC)

*AC for FRQ-022*:  The user shall be able to view Stenosis identified in the vessel or vessels in the Straightened segment.

*AC for FRQ-022.1*: Once the user do Right click on the Stenosis identified, It should display option to "Accept/ Reject/ Edit the name"

*AC for FRQ-022.2*: Once the user does Right click on the Stenosis identified, User should be able to draw a horizontal line to Mark the points of stenosis:  R1-beginning, PM- proximal, O- Max. obstruction point, DM -Distal and R2- end point of stenosis.

*AC FRQC-022.3*:  Stenosis points should be named by the system but if it is manually identified by the user then the user shall be able to points name in the order of R1, PM, O, DM, R2.

*AC for FRQC-022.* | The user shall be able to view different points of Stenosis - R1, PM, O, DM, R2 once it is showing that Stenosis exist in the vessel,
R1 - Start point of Stenosis region; PM: Proximal of Stenosis; O:  Maximum stenosis point; DM - Distal of the Stenosis; R2 - Endpoint of the Stenosis region.

*AC FRQC-022.5* | The user shall be able to move points but they should always remain in this given order  R1, PM, O, DM, R2.

**Comment by yogii1981** [comment]
@samuraimeow : Design this feature and read requirements 
https://docs.google.com/document/d/1E6YJlR15oJ9I2wuXXZvrsW6n8RrBFGm2zr-UnqZB79U/edit#

**Comment by yogii1981** [comment]
updated the requirement of Stenosis @shengt @leeight @samuraimeow

**Comment by leeight** [comment]
> AC for FRQ-022: The user shall be able to view Stenosis identified in the vessel or vessels in the Straightened segment.

![image](https://user-images.githubusercontent.com/104052/34112105-83c6801c-e446-11e7-9cb8-f205acbbb707.png)

----

> AC for FRQ-022.1: Once the user do Right click on the Stenosis identified, It should display option to "Accept/ Reject/ Edit the name"

![image](https://user-images.githubusercontent.com/104052/34112147-a0e4ae94-e446-11e7-921a-f960e15df048.png)

**Comment by leeight** [comment]
@yogii1981 Now you can remove stenosis label order via drag.

![issue-60](https://user-images.githubusercontent.com/104052/34216424-32810d28-e5e3-11e7-9d59-c353cddd63ec.gif)

**Comment by yogii1981** [comment]
@leeight GETTING ERROR : UNDEFINED EFFOR OBJECT WHILE LABELING THE SEGMENTS OF STENOSIS.

**Comment by leeight** [comment]
@yogii1981 Could you post a screenshot for me?

1. The page url
2. The input you typed.

Thanks

**Comment by yogii1981** [comment]
[Screen Shot 2017-12-27 at 10.12.22 AM.pdf](https://github.com/Cleerly/issue-tracker/files/1589289/Screen.Shot.2017-12-27.at.10.12.22.AM.pdf)

**Comment by yogii1981** [comment]
Now I have no idea why R1 has different compare to other in spite of the fact that I am not editing anymore.

**Comment by leeight** [comment]
> why R1 has different compare to other

@yogii1981 If you mean the `different color`, it's a known `(feature/bug)` ;-).

---

> GETTING ERROR : UNDEFINED EFFOR OBJECT WHILE LABELING THE SEGMENTS OF STENOSIS.

I could not reproduce this problem, could you post a screenshot?

**Comment by yogii1981** [comment]
1. when I clicked on Stenosis, I was able to perform an edit in the cross-section view but those changes were not visible in the straightened segment.

2. FRQC-022.1 AND 22.2 _ tested successfully.

3. FRQC-022.3, 22.4 AND 22.5 - UNSUCCESSFUL TEST.

**Comment by leeight** [comment]
OK, I'l add make the stenosis changes sync to other viewports.
