### ISSUE TITLE
Segments - Line should be movable # FRQC 11 # Defect 11

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#3]
<a href="https://github.com/yogii1981"><img src="https://avatars2.githubusercontent.com/u/8645346?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yogii1981](https://github.com/yogii1981)**
_Thursday Nov 30, 2017 at 16:58 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/29_

----

As a user, I should be able to move the segments line so that can rectify incorrectly identified segment location by Mozart.

**Comment by shengt** [comment]
<a href="https://github.com/yogii1981"><img src="https://avatars2.githubusercontent.com/u/8645346?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yogii1981](https://github.com/yogii1981)**
_Friday Dec 01, 2017 at 17:01 GMT_

----

- Unable to move the segments once, I as user selected the Segment. It is restricting the segment movement which is against the functional rule.

**Comment by leeight** [comment]
https://github.com/Cleerly/ccs-web/commit/7ddc338155d1fbdb6cd3a3a373966bc6ea1e1159

**Comment by yogii1981** [comment]
DONE AND TESTED SUCCESSFULLY.
