### ISSUE TITLE
Add physician report page

### ISSUE THREAD

**Issue by leeight** [Cleerly/issue-tracker#39]
Which was used to generate the PDF via <https://github.com/westy92/html-pdf-chrome>

**Comment by leeight** [comment]
cc @shengt

**Comment by leeight** [comment]
![image](https://user-images.githubusercontent.com/104052/33721435-f7f27386-dba1-11e7-93d7-c3a5101723e0.png)

**Comment by leeight** [comment]
@shengt I add a new api in the mockup server, which is used to fetch report information.

```
Url: /lab/cases/:caseId/report
Response:
{
  patient: {....},
  ....
}
```

**Comment by leeight** [comment]
The report page url is: `<endpoint>/#/report/:reportId`

**Comment by shengt** [comment]
@leeight just remove the `/lab` prefix. the report does not belong to visionlab
