### ISSUE TITLE
Upload the DICOM images to Cleerly Cloud and create the study case

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#40]
The data stored in Cleerly Cloud and trigger Cloud's following workflow.
- Create study case in the database
- Create patient information if present
- Set default organization of the study case

Import a study case which DICOM file already saved in S3.
 * The study's patient information will be randomly generated.
 * The facility of the study is hardcoded as Cleerly, Inc

## Acceptance criteria
1. Send POST request to `/import/studies` with payload ```{caseId: xxxxx-xxxxxxxx-xxx-xxx}```
2. Verify if the database has a new study entry with id `xxxxx-xxxxxxxx-xxx-xxx`

**Comment by shengt** [comment]
1. Make sure in AWS S3 `dev_ccs_dcom` bucket, there is a folder named `11a774f5-10bd-4690-9da1-3858b8dc7d11` with dicom files in it.

2. Login with system admin

&nbsp; | value
-- | --
Username | tim.tian@cleerlymed.com
Password | irhUn4eI84g0

Get the auth token in the response

3. send post request with body
```curl -X POST \
  https://dev-api.cleerlymedcloud.com/import/studies \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer xxx.yyy.zzz'
  -d '{"caseId":"11a774f5-10bd-4690-9da1-3858b8dc7d11"}'

**Comment by yogii1981** [comment]
How this use case tested @cleerly-tim ?

**Comment by shengt** [comment]
@yogii1981 , this task has no UI. Please prepare a DICOM files in a folder
1. upload them to S3, `dev_ccs_dcom` bucket, under a <uuid>/dicom/ folder.
2. login to the vision lab portal with the user name password above
3. Get the authorization token from the browser local storage "token" item
4. follow the instruction above to send post request to the server again
