### ISSUE TITLE
Corelab open study case, load dashboard

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#51]
Include CMPR render, 3D artery render, 2D DICOM viewer. Interactive, Segment Variables

**Comment by yogii1981** [comment]
Story has been broken into two stories # 58 and 59

**Comment by yogii1981** [comment]
GETTING ERROR : UNDEFINED EFFOR OBJECT WHILE LABELING THE SEGMENTS OF STENOSIS. @leeight
