### ISSUE TITLE
Dashboard frontend interaction refinement - 3D Coronary Tree and CMPR interaction

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#52]
3D and CMPR interaction.

3D,CMPR 
Requirement: As a user, If I select a point in the CMPR and move my cursor then as I move the cursor in CMPR it should also move in the respective vessel in the 3D coronary Tree simultaneously.

**Comment by yogii1981** [comment]
https://docs.google.com/document/d/1E6YJlR15oJ9I2wuXXZvrsW6n8RrBFGm2zr-UnqZB79U/edit#

**Comment by leeight** [comment]
Duplicated with #60
