### ISSUE TITLE
Corelab review and pass the case,click sent

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#53]
Corelab reviewer loads different series and verify the best series vessel combination. Corelab reviewer check the vessel, segements and variables

**Comment by yogii1981** [comment]
Add story point.

**Comment by leeight** [comment]
This story has already implemented many days ago.

**Comment by yogii1981** [comment]
This Story has been tested was working fine. There is a little change in requirement which we can implement in the upcoming sprints @shengt @leeight cc: @dbooski
