### ISSUE TITLE
FRU-001 Defect Testing - "User unable to login"

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#57]

**Comment by yogii1981** [comment]
https://docs.google.com/document/d/1E6YJlR15oJ9I2wuXXZvrsW6n8RrBFGm2zr-UnqZB79U/edit#heading=h.kipn46a1hw7k



Steps to follow for testing:

1. The User enters the "Username" (registered email address)
2. The user enters valid the "password".
3. The user clicks the "Login" button.

Expected Result: The user should be able to view the Cleerly-HeartVision Provider Dashboard.

Actual Result: The system failed to display the Dashboard.  See attached screenshot. or error 409

**Comment by yogii1981** [comment]
Reported by : Hilary (Email ID)

**Comment by yogii1981** [comment]
@leeight: This is a just a test case ignore it.

**Comment by shengt** [comment]
@yogii1981 when you open a new issue, put the content in the description. A default content with some headers prepopulated.

**Comment by shengt** [comment]
Always choose project and milestone of an issue

**Comment by yogii1981** [comment]
Sure @cleerly-tim
