### ISSUE TITLE
Core-lab Study case uploaded

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#59]
## Functional requirement Number

 2D DICOM viewer. Interactive, Segment Variables

### Steps to reproduce the behavior

| Info | |
| ------------- | ------------- |
| Environment      | xxx | 
| Reported by      | @xxx | 

Or

### Acceptance criteria
1.
2.

**Comment by shengt** [comment]
What's the ticket about? Duplicated with #58 ?

**Comment by leeight** [comment]
Duplicated with #58
