### ISSUE TITLE
 FRQC-020 FRQC-020.1 FRQC-020.2 Add Tracker tool

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#60]
## Functional requirement Number

FRQC-020 | The system shall track the movement of the mouse in all 3 windows simultaneously - Straightened segments, Cross-Section view, and Coronary Tree so that track the movements.

FRQC-020.1 | The system shall display the movement of the tracker simultaneously - Straightened segments, Cross-Section view, and Coronary Tree so that track the movements.
FRQC-020.2 | The system shall have the capability to  hide the tracker

### Summary or detail of the bug

As a user, I should be able to track the position of the mouse in the straightened segment and 3- D Coronary so that as a user I can always know what I am looking at in two different windows.

### Expected behavior

- Tracker visible in the CMPR, cross section and 3- D Coronary tree
- Can hide a tracker whenever the user wants!
### Steps to reproduce the behavior

Or

### Acceptance criteria
1.
2.

**Comment by shengt** [comment]
Does this ticket require UI design? what does the tracker look like? @samuraimeow

**Comment by yogii1981** [comment]
The tool which enables and disable tracker @samuraimeow

**Comment by leeight** [comment]
@shengt Based on the phone call with @tommy-qichang today, we need update some API to support the tracker tool.

If the mouse moves on the straightened vessel viewport, there should be a tracker line across the 4 
straightened vessels, and at the same time, the cross section viewport should render the same slice, the 3d tree viewport should highlight the vessel.

In the API `/lab/cases/:caseId/series/:seriesId/vessels/:vesselId` response, the `cmpr` field's shape should be `64 x 64 x HEIGHT`, so i think we should add a new field, maybe we call it `coords`, it'a array, and length should be `HEIGHT`, and the element in it should be `{x: number, y: number, z:number}`

```js
{
  ...
  cmpr: [],
  coords: [
    {x: 0, y: 0, z: 0},
    ...
    ...
  ]
  ...
}
```

And API `/lab/cases/:caseId/series/:seriesId/vessels/:vesselId/coords` will be obsoleted.

**Comment by leeight** [comment]
![issue-60](https://user-images.githubusercontent.com/104052/33999683-1b279622-e126-11e7-83f6-19c23a5238ec.gif)

@yogii1981 @shengt

**Comment by leeight** [comment]
@yogii1981 @shengt 

The demo environment updated, you can try the tracker tools now.

http://demo.cleerlymedcloud.com/#/case/2

First, click the `[Tracker]` button
Second, move the mouse on the straightened vessel

**Comment by yogii1981** [comment]
why do I have to click on tracker to see the movement of mouse across the the segments and 3-D? @leeight

**Comment by leeight** [comment]
@yogii1981 Now you don't need click the tracker toolbar, Please refresh your page.

**Comment by yogii1981** [comment]
tested successfully.

**Comment by yogii1981** [comment]
It's working fine for series 1 but not for series 2 ? cc: @leeight

**Comment by leeight** [comment]
> It's working fine for series 1 but not for series 2

@yogii1981 It's a known bug, i'll fix it in the future, which not affect the demo.
