### ISSUE TITLE
FRQC-007, 007.1,007.2 Best Combination of series and vessel display 

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#61]
## Functional requirement Number

FRQC-007 | The System by default shall display the best combination of series and vessels as favorites in the upper bar. 
-- | -- | --
FRQC-007.1 | The System shall allow the user to delete particular combination of vessel and series from the favorite list. 
FRQC-007.2 | The System shall allow the user to add the selected combination of series and vessels to favorites in the upper bar. 

## Bug
 NA

### Summary or detail of the bug

NA

### Expected behavior
FRQC-007 - As a user, when I land on the review page, it should display by default the combination of best series and vessels so that I can go through all of them before jumping to other series and their vessels.

FRQC - 007.1 - As a User, I should be able to delete the selected combination of vessel and series from the list of combinations to add the best combination of series and vessels.

FRQC-007.2 - As a user, I should be able to add the best combination of selected vessel and series if that particular vessel is not attached to any other series already.

### Steps to reproduce the behavior

| Info | |
| ------------- | ------------- |
| Environment      | xxx | 
| Reported by      | @xxx | 

Or

### Acceptance criteria
1.
2.

**Comment by leeight** [comment]
@shengt 

The API `/lab/cases/:caseId` should return the `bestSeries` field in as following format:

```js
bestSeries: [
  {seriesId: string, vesselId: string, vesselLabel: string?}
]
```

So that i can display the mozart default bestSeries result on the page initially.

![image](https://user-images.githubusercontent.com/104052/34080869-a934ac92-e37f-11e7-86b3-8271c30496af.png)

**Comment by shengt** [comment]
Hi @leeight , the series array in the /lab/cases/{caseId} is sorted by rank, so the first one is the best series. I've added another key `seriesVesselCombination` to display the vessel information. https://github.com/Cleerly/ccs-api/blob/master/docs/openapi.yml#L1769

**Comment by yogii1981** [comment]
TESTED SUCCESSFULLY.
