### ISSUE TITLE
FRQC-027 - Excluded part of the vessel shouldn't be included in the 

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#63]
## Functional requirement Number

FRQC-027 | The system shall not include the excluded part of the vessel in the volume calculations.
-- | --

## Bug
NA

### Summary or detail of the bug
Na

### Expected behavior

During report generation, 
1. the excluded part of the vessel shouldn't be included in the volume calculation of plaque, stenosis, lumen
2. the excluded part of the vessel shouldn't be included in the area calculation of plaque, stenosis, lumen.

### Steps to reproduce the behavior

| Info | |
| ------------- | ------------- |
| Environment      | xxx | 
| Reported by      | @xxx |

**Comment by yogii1981** [comment]
@shengt @leeight Let me know if you have any question about this requirement.

**Comment by shengt** [comment]
@yogii1981 , I understand what does it mean about the excluded part of the vessel. But I don't understand how can I calculate the area according to the formula. [List of variables- HeartVision for DataScience](https://docs.google.com/spreadsheets/d/18nZv9gJI-zSR3EpzD-_aVBWNnFp8rXkIPRxetXejUos/edit#gid=0)

**Comment by yogii1981** [comment]
@shengt Let's have a call today afternoon to discuss this requirement.

**Comment by yogii1981** [comment]
<img width="575" alt="screen shot 2018-01-02 at 10 19 12 am" src="https://user-images.githubusercontent.com/8645346/34488408-6af13ce2-efa6-11e7-8da5-1973cc5057c7.png">

**Comment by leeight** [comment]
Duplicated with #62 .

**Comment by yogii1981** [comment]
<img width="202" alt="screen shot 2018-01-08 at 12 24 31 pm" src="https://user-images.githubusercontent.com/8645346/34683072-fc58b9cc-f46e-11e7-8458-46a99a633f5a.png">

**Comment by yogii1981** [comment]
Once report generator is built then this feature can be tested. Currently, this feature is dependent on report generator.
