### ISSUE TITLE
Refresh the page kick the user out

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#65]
## Functional requirement Number
NA
## Bug
Refresh the page kick the user out

### Expected behavior
The user should not be logged out after the page reload

### Actual behavior
After login, refresh the page, the user is logged out

### Steps to reproduce the behavior

| Info | |
| ------------- | ------------- |
| Environment      | dev.cleerlymedcloud.com | 
| Reported by      | @shengt | 
| username | tim.tian@cleerlymedcloud.com |
| password | irhUn4eI84g0 |

**Comment by leeight** [comment]
Yes, by design, will fix it later.

**Comment by leeight** [comment]
@shengt 

Should add new API `GET /auth` with `Authorization` header, so that after refresh the page, I can call the API first and check the login status for the current user.

**Comment by shengt** [comment]
Hi @leeight , no API needed here. after the page refresh, your token in the local storage should not be expired, you can use the token again.
