### ISSUE TITLE
FR-001 "Login page unable to open"

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#66]
## Functional requirement Number : FR001 
As I user, Once I enter my valid username and password, and click enter, so the system should display physician Dashboard.

## Bug :
As I clicked Entered, the page login page refreshed itself and username and Password "textbox" were empty.

### Expected behavior
The system Should display the Physician Dashboard

### Actual behavior
Login Page refreshed itself

### Steps to reproduce the behavior

1. Enter Username
2. Enter password
3. Click "Login"

### Acceptance criteria
1. The system Should display the Physician Dashboard

**Comment by shengt** [comment]
@yogii1981 Which environment did you test on?

**Comment by leeight** [comment]
@yogii1981 Could not reproduce, which environment are you using?

**Comment by shengt** [comment]
Close this one because of the `tested by PM` label
