### ISSUE TITLE
FRQC-021.3 Tool : exclusion Line 

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#70]
### Summary or detail of the bug

FRQC-021.3 | For the excluded part in the straightened segment the system shall a provide a tool which allows the user to move the “exclusion part of the straightened segment: Horizontal would be activated which can be moved up and down at both ends of the vessels.After saving the exclusion lines, the vessel walls and lumen walls between two horizontal lines should be annotated.
-- | --

### Expected behavior

1. User able to click on tool " Exclusion line" which activates two horizontal lines on the straightened segment.

2. User able to move the Horizontal line ( which represents the border of excluded part and the vessel segment actually considered)

3. After saving the straightened vessel, the user is able to see annotated vessel wall and lumen wall.

### Actual behavior

2.

**Comment by leeight** [comment]
@yogii1981 The user operate on one straightened vessel and sync the result to other straightened vessels?

**Comment by yogii1981** [comment]
Yes. The result should sync on all the segments. @leeight @cleerly-tim

**Comment by leeight** [comment]
@yogii1981 I see.

**Comment by leeight** [comment]
![issue-70](https://user-images.githubusercontent.com/104052/34677006-b9aab1ba-f4c9-11e7-96c6-97fc5240635a.gif)

**Comment by yogii1981** [comment]
Exclusion tools allow moving the exclusion line up and down in the segmentation.

**Comment by yogii1981** [comment]
Tested successfully.
