### ISSUE TITLE
Normalize coordinates in object format

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#75]
## Feature

Change coordinate format to `{x: 1, y: 1, z: 1}`

- GET `/lab/cases/{caseId}/series/{seriesId}/vessels/{vesselId}`
- PUT `/lab/cases/{caseId}/series/{seriesId}/vessels/{vesselId}`

**Comment by leeight** [comment]
@shengt `wall` 的格式我调整了，`cmpr` 的格式我感觉不应该修改，我在你的那个 commit 上面添加 comment 了，你看看？

**Comment by yogii1981** [comment]
Story Point - 3

**Comment by shengt** [comment]
CMPR的格式我改错了，已经改回来了。那是一个64x64xslices 的三位数组

**Comment by leeight** [comment]
Great.
