### ISSUE TITLE
Display more specific error message

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#8]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leeight](https://github.com/leeight)**
_Thursday Nov 16, 2017 at 15:50 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/5_

----

If the api service return error message, we should display it.

Now we only display the error http response status.

**Comment by leeight** [comment]
FIX IN FUTURE
