### ISSUE TITLE
User is logged out right after log in

### ISSUE THREAD

**Issue by shengt** [Cleerly/issue-tracker#9]
<a href="https://github.com/shengt"><img src="https://avatars0.githubusercontent.com/u/252957?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shengt](https://github.com/shengt)**
_Wednesday Nov 22, 2017 at 20:36 GMT_
_Originally opened as https://github.com/Cleerly/ccs-web/issues/6_

----

Test in https://dev.cleerlymedcloud.com
commit: 2c40ba7f6366bd528b3a7af4b4b1ad9e6a03560a

Username | tim.tian@cleerlymed.com
-- | --
Password | Sh7J49L7ekcJ

1. Login using username and password
See the /auth response a token
2. The client sends the following request to `/cases`. The request has no `Authorization` header attached.
3. The `/cases` responses 401, and the user is logged out.

Checked the local storage, there is no `token` item persisted.

**Comment by shengt** [comment]
<a href="https://github.com/leeight"><img src="https://avatars0.githubusercontent.com/u/104052?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [leeight](https://github.com/leeight)**
_Wednesday Nov 29, 2017 at 13:46 GMT_

----

@shengt Could `https://dev-api.cleerlymedcloud.com` add a whitelist for `Origin: http://localhost:3000`, so that i can debug this issue on my local machine.

**Comment by shengt** [comment]
<a href="https://github.com/shengt"><img src="https://avatars0.githubusercontent.com/u/252957?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shengt](https://github.com/shengt)**
_Thursday Nov 30, 2017 at 03:44 GMT_

----

`http://localhost:3000` has been added to dev

**Comment by shengt** [comment]
from @leeight : @shengt @yogii1981 You should allow X-Request-By request header in the preflight request, which was added days ago.
On demo environment, Nginx will proxy the http request with X-Request-By to the api endpoint.

**Comment by shengt** [comment]
@leeight I've added `X-Request-By` header in the `Access-Control-Allow-Headers` response header. But the request https://dev-api.cleerlymedcloud.com/lab/cases?pageIndex=1&pageSize=10 still does not have `Authorization` header attached.

**Comment by leeight** [comment]
FIXED
